# Generated by Django 6.1 on 2026-08-23 21:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='token',
            field=models.CharField(default=accounts.models.generate_otp, max_length=64, unique=True),
        ),
    ]
