# Generated by Django 6.1 on 2026-08-24 00:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_activationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, validators=[accounts.models.validate_birthdate_not_future], verbose_name='Birthdate'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[accounts.models.validate_facebook_url], verbose_name='Facebook profile'),
        ),
    ]
