# Generated by Django 6.1 on 2026-08-23 03:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_initial_raised_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='initial_raised_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Amount Raised So Far'),
        ),
    ]
