# Generated by Django 6.1 on 2026-08-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_initial_raised_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_manual_critical',
            field=models.BooleanField(default=False, verbose_name='Manually Marked Critical'),
        ),
    ]
