# Generated by Django 6.1 on 2026-08-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_tag_campaign_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
