# Generated by Django 6.1 on 2026-08-25 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_tag_options_campaignrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Fraud or Misleading', 'Fraud or Misleading Information'), ('Inappropriate Content', 'Inappropriate Content'), ('Spam or Scam', 'Spam or Scam'), ('Other', 'Other')], default='Other', max_length=50)),
                ('details', models.TextField(help_text='Detailed description of the issue.')),
                ('status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Reviewed', 'Reviewed'), ('Dismissed', 'Dismissed'), ('Action Taken', 'Action Taken')], default='Pending Review', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='campaigns.campaign')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
