# Generated by Django 6.1 on 2026-08-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_comment_commentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured Campaign'),
        ),
    ]
